### ISSUE TITLE
share short link dd.tt

### ISSUE THREAD

**Issue by maurerr** [severach/Dropbox-Uploader#3]
Hi,

Can we have url shortening like in orginal script?

Thanks

**Comment by severach** [comment]
I fixed the short URL with a deprecated APIv2 call. To be sure this will work forever, ask Dropbox to add the short URL to the new API call.

**Comment by maurerr** [comment]
you forgot to mention one has to turn on url shortening :) via:
SHORT_URL='true'
default is false in dropbox_uploader.sh

**Comment by severach** [comment]
Try option -u
